In [4]:
import numpy as np

**One-dimensional Array**

In [2]:
np_array1 = np.array([1,2,3,4,5,6,7,8,9]) 

In [3]:
print(np_array1)

[1 2 3 4 5 6 7 8 9]


In [4]:
np_array.shape

(9,)

**Two-dimensional Array**

In [20]:
np_array2 = np.array([1,2,3,4,5,6,7,8,9])

In [39]:
np_array2.shape

(9,)

In [8]:
np_array2 = np_array2.reshape(3,3)

In [9]:
np_array2.shape

(3, 3)

In [11]:
np_array2.ndim

2

**Type name of Array**

In [13]:
np_array2.dtype.name

'int32'

**Number of elements in Array**

In [17]:
print(np_array2.size)

9


**Type of Array**

In [18]:
type(np_array)

numpy.ndarray

**Array of Zeros**

In [23]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Array of Ones**

In [24]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Empty Array**

In [40]:
empty = np.empty((3,3))
empty

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Arange**

In [29]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

**Line space**

In [30]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

**Using with Operations**

In [33]:
a = np.array([1,2,3])

In [32]:
b = np.array([6,5,4])

In [34]:
print(a+b)

[7 7 7]


In [35]:
print(a-b)

[-5 -3 -1]


In [36]:
print(a*b)

[ 6 10 12]


In [42]:
py_array = [1,2,3,4,5]

In [43]:
np_array = np.array([1,2,3,4,5])

In [45]:
print(py_array)
print(np_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


**Copy Array**

In [52]:
a = np.array([1,2,3])

In [47]:
b = a
c = a

In [49]:
b[0] = 0

In [50]:
print(a,b,c)

[0 2 3] [0 2 3] [0 2 3]


In [53]:
a

array([1, 2, 3])

In [54]:
a = np.array([1,2,3])

In [55]:
b = a.copy()
c = a.copy()

In [57]:
b[0] = 0

In [58]:
print(a,b,c)

[1 2 3] [0 2 3] [1 2 3]


**Indexing**

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(a[:4])

[1 2 3 4]


In [9]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b[1,1]

5

**Row**

In [14]:
print(b[:,1])

[2 5 8]


**Column**

In [15]:
print(b[1,:])

[4 5 6]


In [16]:
print(b[1,1:4])

[5 6]


**End of row**

In [17]:
print(b[-1,:])

[7 8 9]


**End of column**

In [18]:
print(b[:,-1])

[3 6 9]


**Ravel()**

In [19]:
np.ravel(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b = b.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b.resize(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])